- python/coglet/__main__.py
> Add missing return type annotation

- .github/workflows/ci.yml
- TODO.md
- internal/server/runner.go
- internal/server/types.go
- internal/tests/async_prediction_test.go
- internal/tests/prediction_test.go
- internal/tests/setup_test.go
- script/check.sh
- script/test.sh
- **Refactor webhook**
- **Make statuses consts**
- **Send webhooks at 500ms interval**
- **Add webhook_events_filter to TODO**
> Improve web hook handling

- internal/server/runner.go
- internal/tests/async_prediction_test.go
- internal/tests/async_predictor_test.go
- **Remove unused RESPONSE_FMT**
- **Fix webhook intervals**
> Fix webhook intervals

- TODO.md
- cmd/cog-server/main.go
- cmd/webhook/main.go
- internal/server/path.go
- internal/server/runner.go
- internal/server/types.go
- internal/tests/async_prediction_test.go
- internal/tests/async_predictor_test.go
- internal/tests/cog_test.go
- internal/tests/iterator_test.go
- internal/tests/path_test.go
- **Fix input path garbage collection**
- **Fix webhook server logging**
- **Use log.Fatalw instead of panic**
- **Support file upload**
> Support file upload

- internal/server/runner.go
- internal/tests/cog_test.go
- python/pyproject.toml
- script/cog-server.sh
- script/init.sh
- script/schemas.sh
- **Create venv with legacy Cog**
- **Support testing with legacy Cog**
> Support testing with legacy Cog

- internal/server/http.go
- internal/server/runner.go
- internal/server/server.go
- internal/tests/async_prediction_test.go
- internal/tests/async_predictor_test.go
- internal/tests/cog_test.go
- internal/tests/filter_test.go
- internal/tests/iterator_test.go
- internal/tests/path_test.go
- python/coglet/_compat/cog/__init__.py
- python/coglet/_compat/cog/server/exceptions/__init__.py
- python/coglet/api.py
- python/coglet/file_runner.py
- python/coglet/runner.py
- python/tests/runners/async_sleep.py
- python/tests/runners/sleep.py
- python/tests/test_file_runner.py
- python/tests/test_file_runner_async.py
- **Support cancel**
- **Improve HTTP error handling**
> Support cancel

- python/coglet/adt.py
- python/coglet/api.py
- python/coglet/inspector.py
- python/coglet/runner.py
- python/coglet/schemas.py
- python/tests/schemas/defaults_none.json
- python/tests/schemas/defaults_none.py
Cog allows None as default value while absence of default kwarg means
the field is required
> Handle default=None vs missing default

- internal/server/path.go
- internal/server/runner.go
- internal/tests/path_test.go
- python/coglet/file_runner.py
- **Remove FIXME on eager import & wait**
- **Download input files**
Rework #37 as Go only
> Download input files

- .gitignore
- pyproject.toml
and report to term and html for both quick feedback and detailed feedback when desired.
> Run pytest with cov

- python/coglet/adt.py
- python/coglet/inspector.py
- python/coglet/schemas.py
- python/coglet/util.py
- python/tests/cases/repetition.py
- python/tests/test_cases.py
- python/tests/test_predictors.py
- python/tests/test_util.py
- script/check.sh
* Support `<T>`, `Optional[<T>]` and `List[<T>]` as repetition levels
* `default=None` or absence means `None` default value for optional fields i.e. `x: Optional[T]`
* Otherwise the field is required
> Refactor field repetition

- python/cog/coder/dataclass_coder.py
- python/cog/coder/json_coder.py
- python/coglet/runner.py
- python/tests/runners/typeddict_obj.py
* Check if the type is subclassing dict to ensure TypedDict gets treated as a JSON type
Necessary for supporting anthropics `MessageParams` `TypedDict`
> Add TypedDict support to json coder

- python/coglet/inspector.py
- python/tests/runners/setup_default_args.py
* Allow for args with defaults to be included in setup
> Validate setup against non default parameter args

- python/coglet/file_runner.py
- python/coglet/scope.py
* Reduce string search & replace overhead
* Clean up buffer after prediction completed
* Fix a subtle bug of prefix handling
> Optimize ctx_write

- python/coglet/file_runner.py
- python/tests/procedures/bar/predict.py
- python/tests/procedures/foo/predict.py
* Replicate python client looks for this key in the context dictionary: https://github.com/replicate/replicate-python/blob/0110c2c5639763a44e73d69011eaec28a15334f7/replicate/client.py#L356
> Use correct dictionary key

- internal/server/http.go
- internal/tests/procedure_test.go
* Add a new endpoint for procedures to be explicitly called from
* This endpoint is currently the same as predictions
* After director talks to this endpoint (once this is merged and then director is up and running with the changes, the logic for procedures will be moved from handler.Predict to a new handler.Procedures function
> Add procedures URLs

- internal/server/runner.go
- internal/server/types.go
- python/coglet/__main__.py
- python/coglet/file_runner.py
- python/tests/test_file_runner.py
- python/tests/test_file_runner_async.py
In async mode, server is ready when pending predictions < max concurrency, not when any prediction is running
> Fix readiness in async mode

- internal/tests/procedure_url_test.go
- internal/util/procedure.go
* Copy procedure directory into a temporary directory using symlinks
> Recursive symlink copy procedure directory

- internal/server/runner.go
- python/tests/procedures/cog.yaml
- **Remove unused procedures/cog.yaml**
- **Log runner configuration in Go server**
> Procedure fixes

- internal/server/runner.go
- internal/server/server.go
- python/coglet/file_runner.py
- **Fix regex constant casing**
- **Reorder runner methods**
- **Reset failed procedure runner**
- **Tweak Python runner ready/busy flip**
> Various tweaks

- internal/server/path.go
- internal/tests/path_test.go
- **Set fallback location on upload**
- **Fix output path test for legacy Cog**
> Fix upload tests

- .github/workflows/ci.yml
* Upload the distribution folder to R2
> Upload python package distribution to R2

- python/cog/command/call_graph.py
* Deduplicate usages of `replicate.use`
> Deduplicate includes

- internal/tests/cog_test.go
- script/cog-procedure.sh
- script/init.sh
because it is no longer used in this way.
> Remove references to and usage of `pipelines-runtime` repo

- internal/server/runner.go
* Some models return a hard-coded baked-in file, do not delete them
> Do not delete output file

- internal/server/http.go
- internal/server/runner.go
- internal/server/server.go
- internal/tests/procedure_test.go
- python/tests/procedures/setuid/predict.py
- script/test-setuid.sh
* Use a [] instead map for runners
* So that array offset is the slot id, e.g. [0]: '00:/src/foo', [1]: '01:/src/bar'
* nil indicates an empty slot
> Fix runner slot computation

- cmd/cog/main.go
- internal/server/server.go
- internal/tests/cog_test.go
- internal/util/util.go
- python/coglet/__main__.py
* Create go loggers from common path that reads env var
* Set coglet log level to COG_LOG_LEVEL
> Support COG_LOG_LEVEL

- python/coglet/api.py
* pyodide has a curious issue where it does not recognise BaseModel as a dataclass
* It is defined as a dataclass through its use of __new__ which standard python accepts
* To get around this, make a new base model for pyodide which uses __init_subclass__
* Decide which implementation to use depending on whether we are in pyodide
> Add pyodide specific BaseModel
