python/coglet/_compat/cog.py

so that `python -c 'import cog;print(cog.__version__)'` does not blow up and is arguably useful.

Add pseudo-version to cog compat layer

---

cmd/cog-server/main.go
go.mod
internal/server/path.go
internal/server/runner.go
internal/server/types.go
internal/tests/async_prediction_test.go
internal/tests/cog_test.go
internal/tests/prediction_test.go
internal/tests/setup_test.go
internal/util/util.go
python/coglet/file_runner.py
script/cog-server.sh

- **Remove redundant coglet/_compat from PYTHONPATH**
- **Remove --working-dir from cog-server.sh**
- **Log await-explicit-shutdown**
- **Use any instead of interface{}**
- **Reset ctx_pid before logging on prediction cancel or failure**
- **Add tests**

Add E2E tests

---

.github/workflows/ci.yml
internal/server/runner.go
internal/tests/async_prediction_test.go
internal/tests/async_predictor_test.go
internal/tests/cog_test.go
internal/tests/filter_test.go
internal/tests/iterator_test.go
internal/tests/path_test.go
internal/tests/prediction_test.go
internal/tests/setup_test.go
python/tests/runners/path.py
script/test.sh

- **Handle legacy Cog in setup_test**
- **Handle legacy Cog in prediction_test**
- **Improve prediction failed handling**
- **Prevent concurrent webhooks on the same prediction**
- **Handle legacy Cog in path_test**
- **Handle legacy Cog in iterator_test**
- **Handle legacy Cog in filter_test**
- **Handle legacy Cog in async_prediction_test**
- **Skip async_predictor_test when testing legacy Cog**
- **Add CI for legacy Cog tests**

Test against legacy Cog

---

internal/server/http.go
internal/server/runner.go
internal/server/server.go
internal/tests/async_prediction_test.go
internal/tests/cog_test.go
internal/tests/prediction_test.go
python/coglet/runner.py

- **Reorder methods in Runner**
- **Test prediction concurrency**
- **Simplify prediction test helpers**

Test prediction concurrency

---

internal/server/runner.go
internal/tests/async_prediction_test.go
internal/tests/async_predictor_test.go
internal/tests/cog_test.go
internal/tests/filter_test.go
internal/tests/iterator_test.go
internal/tests/path_test.go
internal/tests/prediction_test.go

* Run legacy Cog with PYTHONUNBUFFERED
* Send "processing" instead of "start" webhook
* Simplify webhook sequence assertions

Improve legacy Cog compliance

---

cmd/cog/main.go
python/cog/command/test.py
python/coglet/inspector.py
python/coglet/runner.py
python/coglet/schema.py
python/coglet/test.py
python/tests/runners/async_iterator.py
python/tests/runners/async_sleep.py
python/tests/runners/concat_iterator.py
python/tests/runners/iterator.py
python/tests/runners/output.py
python/tests/runners/path.py
python/tests/runners/sleep.py
python/tests/runners/tqdm_out.py
python/tests/test_test_inputs.py

* Check for `predictor.test_inputs` in `coglet.schema` command.
* If `test_inputs` is missing, each `Input` must have a default value and they'll be used for testing
* `test_inputs` will be type checked with the same logic when running normal prediction loop
* Run `predictor.predict()` with `test_inputs` in `coglet.test`
* Add `python3 -m cog.command.test` entrypoint for consistency

Add test_inputs

---

python/tests/test_file_runner_async.py

The async tests are flaky and usually missing 1 signal on the LHS, possibly due to delay between output file and signal received by supervisor process.

Increase signal wait in async tests

---

internal/server/runner.go

So that we can include logs received so far in setup time out result.

Make setup logs live in /health-check

---

internal/server/runner.go

Add logs from subprocesses, only if in blocking mode
Run `./script/cog-predict.sh path` with the following modification
```
diff --git a/python/tests/runners/path.py b/python/tests/runners/path.py
index 479376f..f9d8eb1 100644
--- a/python/tests/runners/path.py
+++ b/python/tests/runners/path.py
@@ -1,5 +1,7 @@
import tempfile
import time
+import subprocess
+import sys
from cog import BasePredictor, Path
@@ -9,6 +11,7 @@ class Predictor(BasePredictor):
def predict(self, p: Path) -> Path:
time.sleep(0.1)
+        subprocess.run(["echo", "hello"], check=True)
with open(p, 'r') as f:
print('reading input file')
s = f.read()
```
In the output logs you should see
```
"logs":"hello\nreading input file\nwriting output file\n"
```

Add logs from subprocesses

---

python/cog/command/call_graph.py

* This mirrors the call_graph command on cog
* Retrieves a list of model dependencies and fails when they aren’t statically available

Add call_graph to cog-runtime

---

cmd/cog/main.go
internal/server/openapi-procedure.json
internal/server/runner.go
internal/server/server.go
internal/server/types.go
internal/tests/cog_test.go
internal/tests/procedure_test.go
internal/util/util.go
python/coglet/file_runner.py
python/coglet/scope.py
python/tests/procedures/bar/cog.yaml
python/tests/procedures/bar/predict.py
python/tests/procedures/cog.yaml
python/tests/procedures/foo/cog.yaml
python/tests/procedures/foo/predict.py
script/cog-procedure.sh
script/init.sh

Rework of #74 to maximize reuse of the go `Runner` & add integration test.
* Right now only 1 active procedure. New request with a different procedure URL will stop the current runner (gracefully, so it will finish pending requests and send web hooks) and replace it with the new one.
* Integration test with legacy cog requires the private `pipelines-runtime` to be checked out into a sibling directory. So it's skipped right now in CI.
* Now that we're no longer using a fake wrapper model, can we move `procedure_source_url` & `token` to prediction request top level, and keep original `input` as is instead of JSON in JSON?
`{"procedure_source_url": "file://tmp/x", "token": "foo", "input": {"s": "hello"}}`
* Found 2 issues with legacy Cog:
* Bug where logs from different procedures are mixed …

Support procedure mode

---

internal/server/runner.go
internal/server/server.go
internal/tests/cog_test.go
internal/tests/procedure_url_test.go
internal/util/find_port.go
internal/util/procedure.go

* If someone has a URL path for a procedure that contains multiple directories this currently fail
* Hash the path so the directories are standardised

Prepare procedure source URL for remote tarballs

---

internal/server/server.go
internal/tests/procedure_test.go
pyproject.toml
python/coglet/file_runner.py

This PR renames the `token` key in the prediction request context to `replicate_api_token`. Ultimately I don't think this is needed at all, the context just needs to be passed along and made available via the `current_scope().context`. But this is the smallest change to get us unblocked.

Use `replicate_api_token` instead of `token`

---

python/coglet/adt.py
python/coglet/util.py
python/tests/schemas/output_pathlike.json
python/tests/schemas/output_pathlike.py

This will ensure that it supports anything that conforms to `os.PathLike` including `pathlib.PosixPath`.

Support predictors returning `os.PathLike` instances

---

cmd/cog/main.go
internal/server/http.go
internal/server/runner.go
internal/server/server.go
internal/tests/cog_test.go
internal/tests/procedure_test.go
internal/tests/setup_test.go
internal/tests/shutdown_test.go

* Ignore SIGTERM if --await-explicit-shutdown is set
* Move shutdown responsibility up from runner to server
* Add tests

Re-work shutdown sequence

---

internal/server/server.go
python/coglet/file_runner.py

We need to wait for a procedure runner to finish setup before it can be
added to the runner pool, which means we cannot handle READY IPC for
that runner yet. Instead use a READY file and polling.

Handle procedure runner starting and IPC race condition

---

internal/server/runner.go
internal/tests/cog_test.go
internal/tests/logs_test.go
python/cog/command/go_cog.py
python/coglet/__main__.py
python/tests/runners/logs.py

Pipe stdout/stderr of the Python runner process to corresponding streams of the Go process.
Also override `LOG_FILE=stderr` so that it matches legacy Cog logging behavior.

Pipe Python stdout/stderr to the same streams in Go

---

internal/server/server.go
internal/util/procedure.go
script/test-setuid.sh

Symlinks are not readable if the parent directory of src URL is not readable by the unprivileged user. So copy everything and chown after to avoid that.

Copy procedure dir instead of symlink

---

python/coglet/adt.py
python/coglet/inspector.py
python/tests/bad_predictors/input_enum_choices.py
python/tests/bad_predictors/input_enum_default.py
python/tests/schemas/enums.json
python/tests/schemas/enums.py

Allow enums in `default` & `choices` fields of `Input`.
* Enum must extend the same field type, e.g. `Class Colors(str, Enum)` for `c: str=Input(default=Colors.RED)`
* Extract the enum value e.g. `RED = "red"` as inputs

Support enums

---

internal/server/runner.go
internal/server/server.go

Previously the readiness probe file was only written in procedure mode after the schema was available, but procedures are loaded async, which means k8s never sees the pod as ready

Write the readiness probe on boot in procedure mode

---

cmd/cog/main.go
cmd/webhook/main.go
internal/server/http.go
internal/server/runner.go
internal/server/server.go
internal/tests/cog_test.go
internal/tests/prediction_test.go
internal/tests/procedure_url_test.go
internal/tests/setup_test.go
internal/tests/shutdown_test.go
internal/util/find_port.go
internal/util/util.go

This change eliminates runtime panics in the runner and server. General code hygiene dictates that we should never crash for a recoverable error. This commit removes use of `replicate/go/must` in the runner and server.
Eliminated the use of must and associated panics across all runtime code paths, all go tests, and both `main.go` files.
Testing use of `must` while convenient encourages use of `panic` instead of actual validation.
Idiomatic go does not panic under normal circumstances.

No Runtime Panics/No `replicate/go/must`

---

python/coglet/file_runner.py
python/coglet/inspector.py
python/coglet/schema.py
python/tests/cases/repetition.py
python/tests/test_bad_predictor.py
python/tests/test_cases.py

So that we only turn it off when starting a model but keep it on for cog.command.openapi_schema and all tests.

Flip inspect_ast conditions

---

cmd/cog/main.go
internal/server/runner.go
internal/server/runner_test.go
internal/server/server.go
internal/server/types.go
internal/tests/harness_test.go

This commit implements a forcekill mechanism for the runner. This ensures that we are no longer leaking resources once the runner is shutdown.
Implementation details:
- `runner.ForceKill()` implemented
- process groups are now in place for all uses of exec.CommandContext
- uses `cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}`
- Migrated to exec.CommandContext to give a proper lifecycle to the CMD
- LegacyCog smoke test also has an explicit ForceKill functionality
- Comprehensive Unit test for ForceKill has been added
- Test Harness leaverages a graceperiod of 0 to kill runners immediately
- Main cli can pass a fixed graceperiod for runners, with a default value

feat: Implement ForceKill

---

internal/tests/input_function_test.go
pyproject.toml
python/coglet/api.py
python/coglet/inspector.py
python/tests/runners/input_function.py
python/tests/runners/input_simple.py
python/tests/schemas/input_function_test.json
python/tests/test_input_function.py
python/tests/test_input_functional.py

Convert Input from dataclass to function with overloads following Pydantic's pattern. Maintains exact same syntax for developers while providing full type checker compatibility.
Key changes:
- Add Input() function with @overload decorators returning Any for type checkers
- Create FieldInfo dataclass to store field metadata at runtime
- Update inspector.py to use FieldInfo instead of Input dataclass
- Add comprehensive test suite (31 unit/functional tests + Go integration)
- Fix BaseModel inheritance tests with proper type annotations and getattr usage

Implement type checker compatible Input() function

---

.github/workflows/ci.yml
internal/tests/coder_test.go
python/coglet/adt.py
python/tests/runners/custom_output.py
python/tests/test_basemodel_inheritance.py

The name `Output` has no bearing on if the output type is valid.
Additionally, since BaseModel is a simple wrapper (essentially syntactic
sugar) to wrap dataclass around an output, support generic dataclass
outputs.

Support Complex datatype output

---

internal/runner/manager.go

The slot release was incorrect and was run outside of the manager.predict function meaning we effectively had more slots than expected.
This change eliminates the added .releaseSlot() call in the wrong method.

Correct a spurious slot release

---

internal/runner/manager.go
internal/runner/path.go
internal/runner/path_test.go
internal/runner/runner.go
internal/runner/runner_test.go
internal/runner/types.go
internal/server/server.go
internal/tests/async_prediction_test.go
internal/tests/async_predictor_test.go
internal/tests/filter_test.go
internal/tests/iterator_test.go
internal/tests/path_input_regression_test.go
internal/tests/path_test.go
internal/tests/prediction_test.go
internal/tests/procedure_schema_test.go
internal/tests/shutdown_test.go
python/tests/procedures/path_test/cog.yaml
python/tests/procedures/path_test/predict.py
python/tests/runners/path_input_https.py

Schema wasn't loaded prior to processing the input paths this resulted in a noop nil response. To ensure we always load the schema first we now block on runner ready state before processing. Additionaly a nil doc is considered an error. In the cases we call ProcessInputPaths we can accept that error; in manager we explicitly check for doc being nil and emit an error log.

bugfix: Ensure schema is loaded before processing
